# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code 
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Pre-Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  release:
    needs: build
    runs-on: ubuntu-latest


    steps:
      - name: Debug Token Permissions
        run: |
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user/repos

      - name: Create Pre-release
        id: Create_pre-release
        uses: actions/create-pre-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.${{ github.run_number }}
          release_name: Pre-release 0.${{ github.run_number }}
          draft: false
          prerelease: true


