# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code 
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Pre-Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      -  run: npm ci

      - name: Build
        run: npm run build

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug Token Permissions
        run: |
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          curl -H "Authorization: token $GITHUB_TOKEN"

      - name: Create Release
        id: Create_Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.${{ github.run_number }}
          release_name: release 0.${{ github.run_number }}
          draft: false
          prerelease: true


